"""Collect every results/fc_*.json and results/density_*.json into Markdown tables.

Usage:
    python scripts/04_summary_tables.py            -> results/summary_tables.md
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import common as C  # noqa: E402


def main() -> int:
    lines = ["# Summary tables (auto-generated by scripts/04_summary_tables.py)", ""]

    fc_files = sorted(C.RESULT_DIR.glob("fc_*.json"))
    if fc_files:
        lines += [
            "## Force-constant partition of the O···O stretch",
            "",
            "k_X = d²X/dR² at R_min (kcal/mol/Å²); f_X = k_X / k_total; ω from k_total with μ = m(H₂O)/2.",
            "CT = electrons lost by the acceptor at R_min (acceptor → donor), Mulliken / IAO.",
            "",
            "| tag | δr(O–H) Å | R_min Å | E_int | k_total | ω(H₂O) cm⁻¹ | ω(D₂O) | f_Elec | f_Exch | f_Rep | f_ExRep | f_OrbRel | f_Corr | f_Disp | f_CorrDisp | CT Mull | CT IAO | dCT/dR IAO |",
            "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
        ]
        for f in fc_files:
            d = C.load_json(f)
            c = d["components"]
            ct = d["charge_transfer_acceptor"]
            mull = ct["mulliken"]["value_e"] if ct.get("mulliken") else float("nan")
            iao = ct["iao"]["value_e"] if ct.get("iao") else float("nan")
            iao_s = ct["iao"]["slope_e_per_A"] if ct.get("iao") else float("nan")
            lines.append(
                f"| {d['tag']} | {d.get('oh_elongation_angstrom', 0.0):.3f} | {d['R_min_A']:.4f} | {d['E_int_min_kcal']:.3f} | "
                f"{d['k_total_kcal_per_A2']:.3f} | {d['omega_H2O_cm-1']:.1f} | {d['omega_D2O_cm-1']:.1f} | "
                f"{c['Elec']['fraction_of_k']:+.3f} | {c['Exch']['fraction_of_k']:+.3f} | {c['Rep']['fraction_of_k']:+.3f} | "
                f"{c['ExRep']['fraction_of_k']:+.3f} | {c['OrbRel']['fraction_of_k']:+.3f} | {c['Corr']['fraction_of_k']:+.3f} | "
                f"{c['Disp']['fraction_of_k']:+.3f} | {c['CorrDisp']['fraction_of_k']:+.3f} | {mull:+.4f} | {iao:+.4f} | {iao_s:+.4f} |"
            )
        lines += ["", "### Absolute k_X (kcal/mol/Å²)", "",
                  "| tag | k_Elec | k_Exch | k_Rep | k_OrbRel | k_Corr | k_Disp | k_total | Σ slopes | max closure Eh |",
                  "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
        for f in fc_files:
            d = C.load_json(f)
            c = d["components"]
            lines.append(
                f"| {d['tag']} | {c['Elec']['k_kcal_per_A2']:.3f} | {c['Exch']['k_kcal_per_A2']:.3f} | {c['Rep']['k_kcal_per_A2']:.3f} | "
                f"{c['OrbRel']['k_kcal_per_A2']:.3f} | {c['Corr']['k_kcal_per_A2']:.3f} | {c['Disp']['k_kcal_per_A2']:.3f} | "
                f"{d['k_total_kcal_per_A2']:.3f} | {d['force_balance_sum_of_slopes']:.4f} | {d['max_abs_closure_hartree']:.1e} |"
            )
        lines.append("")

    dens_files = sorted(C.RESULT_DIR.glob("density_*.json"))
    if dens_files:
        lines += [
            "## Density at the H-bond saddle point (minimum of ρ_final between H_b and O_a on the O···O line)",
            "",
            "Fractions are relative to ρ_final. ρ in e/bohr³.",
            "",
            "| tag | R_OO Å | d(saddle–H_b) Å | ρ_final | ρ₀ | Δρ_Pauli | Δρ_relax | ρ₀/ρ_final | Δρ_Pauli/ρ_final | Δρ_relax/ρ_final | E_int | OrbRel | CT IAO |",
            "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
        ]
        for f in dens_files:
            d = C.load_json(f)
            ct_label = d.get("ct_label", "acceptor")
            for rec in d["records"]:
                s = rec["saddle"]
                lines.append(
                    f"| {d['tag']} | {rec['R_OO']:.3f} | {s['distance_from_Hb_A']:.3f} | {s['rho_final']:.5f} | {s['rho_0']:.5f} | "
                    f"{s['d_rho_pauli']:+.5f} | {s['d_rho_relax']:+.5f} | {s['fraction_promolecule']:.3f} | {s['fraction_pauli']:+.3f} | "
                    f"{s['fraction_relax']:+.3f} | {rec['components_kcal']['Total']:.3f} | {rec['components_kcal']['OrbRel']:.3f} | "
                    f"{rec['iao_ct'].get(ct_label, float('nan')):+.4f} |"
                )
        lines.append("")

    out = C.RESULT_DIR / "summary_tables.md"
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"# wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
